import type { Locale } from "@wlbp/i18n";
const labels: Record<string, readonly [string, string]> = {
  open: ["Open", "مفتوح"],
  resolved: ["Resolved", "محلول"],
  urgent: ["Urgent", "عاجل"],
  warning: ["Warning", "تنبيه"],
  normal: ["Normal", "عادي"],
  written_off: ["Written off", "شُطب"],
  contested: ["Contested", "متنازع عليه"],
  reconciled: ["Reconciled", "تمت التسوية"],
  no_action_needed: ["No action needed", "لا يلزم إجراء"],
  not_sent: ["Not sent", "لم يُرسل"],
  requires_action: ["Action required", "يلزم إجراء"],
  partially_refunded: ["Partially refunded", "استرداد جزئي"],
  requested: ["Requested", "طلب حجز"],
  confirmed: ["Confirmed", "مؤكد"],
  checked_in: ["Checked in", "تم تسجيل الحضور"],
  completed: ["Completed", "مكتمل"],
  no_show: ["No-show", "لم يحضر"],
  cancelled: ["Cancelled", "ملغي"],
  expired: ["Expired", "منتهي"],
  pending: ["Pending", "قيد الانتظار"],
  queued: ["Queued", "في قائمة الانتظار"],
  sending: ["Sending", "جارٍ الإرسال"],
  sent: ["Sent to provider", "تم الإرسال للمزود"],
  delivered: ["Delivered", "تم التسليم"],
  failed: ["Failed", "فشل"],
  suppressed: ["Suppressed", "تم منع الإرسال"],
  not_required: ["Not required", "غير مطلوب"],
  succeeded: ["Succeeded", "نجح"],
  active: ["Active", "نشط"],
  inactive: ["Inactive", "غير نشط"],
  revoked: ["Revoked", "ملغى الصلاحية"],
  draft: ["Draft", "مسودة"],
  published: ["Published", "منشور"],
  retired: ["Retired", "متوقف"],
  disconnected: ["Disconnected", "غير متصل"],
  restricted: ["Restricted", "مقيد"],
  suspended: ["Suspended", "معلق"],
  requirements_due: ["Requirements due", "متطلبات مطلوبة"],
  connected: ["Connected", "متصل"],
  error: ["Unavailable", "غير متاح"],
  processing: ["Processing", "قيد المعالجة"],
  paid: ["Paid", "مدفوع"],
  unpaid: ["Unpaid", "غير مدفوع"],
  refunded: ["Refunded", "تم الاسترداد"],
  not_configured: ["Not configured", "غير مهيأ"],
  accepted: ["Accepted", "مقبول"],
  declined: ["Declined", "مرفوض"],
  approved: ["Approved", "تمت الموافقة"],
  rejected: ["Rejected", "مرفوض"],
  not_applicable: ["Not applicable", "لا ينطبق"],
};
export function workspaceStatus(locale: Locale, value: string): string {
  return (
    labels[value]?.[locale === "ar" ? 1 : 0] ??
    (locale === "ar" ? "حالة غير معروفة" : "Unknown status")
  );
}
