import { formatPlural, type Locale, type PluralForms } from "@wlbp/i18n";

/*
 * Workspace frame and operations-screen copy that is not part of the main
 * dashboard catalogue: shell controls, the Today schedule, and plural forms.
 * Every key exists in English and Arabic (enforced by workspace-copy.test.ts).
 */
export const workspaceCopy = {
  en: {
    skipToContent: "Skip to main content",
    openMenu: "Open navigation menu",
    closeMenu: "Close navigation menu",
    closeDialog: "Close",
    themeToDark: "Switch to dark theme",
    themeToLight: "Switch to light theme",
    languageSwitch: "Language",
    currentWorkspace: "Current workspace",
    liveConnecting: "Connecting",
    liveConnected: "Live",
    liveUnavailable: "Live unavailable",
    liveReconnecting: "Reconnecting",
    liveRefused: "Access check",
    newBooking: "New booking",
    todayWindow:
      "Window: the default location’s full civil day; appointment times use their own locations.",
    timeZoneLabel: "Time zone",
    scheduleTitle: "Day schedule",
    scheduleLabel: "Bookings on {date}, one band per team member",
    scheduleEmptyLane: "No bookings",
    scheduleEmptyDay: "No appointments today. Upcoming bookings are listed below.",
    scheduleUnassigned: "Unassigned",
    scheduleUnknownMember: "Team member",
    scheduleUnknownResource: "Resource",
    agendaLabel: "The day’s bookings in time order",
    requestsColumnTitle: "Awaiting a decision",
    requestsColumnEmpty: "No requests are waiting for a decision.",
    reviewRequest: "Review request",
    reviewPayment: "Review payment",
    reviewCommunications: "Review messages",
    nowAt: "Now: {time}",
    foldLabel: "Occurrence for a repeated local time",
    foldNone: "Unambiguous time",
    foldFirst: "First occurrence",
    foldSecond: "Second occurrence",
    calendarHour: "Hour",
    calendarTimetable: "Calendar timetable",
    calendarTimetableCaption: "Start times in the selected time zone",
    calendarNoResource: "No resource allocation",
    calendarResourceLabel: "Bookings on {date}, one band per resource",
    relatedPages: "Related pages",
    bookingChange: "Booking change",
    actorStaff: "Staff",
    actorGuest: "Customer",
    actorSystem: "System",
    actorWorker: "Background worker",
    actorUnknown: "Actor",
    reportsLocation: "Location",
    reportsAllLocations: "All permitted locations",
    jobExport: "Data export",
    jobDeletion: "Deletion",
    jobKind: "Request",
    refundAttempts: "Attempts",
    utilizationMember: "Team member",
    utilizationMinutes: "Booked / offered minutes",
    refundFailure: "Failure code",
    jobCreated: "Opened",
    jobProgress: "Progress",
    noteSensitivityLabel: "Visibility",
    filtersLabel: "Filters",
    pendingRequestsBadge: "Pending requests",
    workspaceSwitcherHint: "Your memberships",
    reference: "Reference",
    service: "Service",
    customer: "Customer",
    actions: "Actions",
    rescheduleOrCancel: "Reschedule, cancel or resend",
    lifecycleActions: "Lifecycle actions",
    exportReveal: "Export contents",
    notFoundCode: "Error 404",
    signOutLabel: "Sign out",
    timesShownIn: "Time zone for this page",
    datePlaceholder: "Choose a date",
    timePlaceholder: "Choose a time",
    timeOf: "{label}, time",
  },
  ar: {
    skipToContent: "انتقل إلى المحتوى الرئيسي",
    openMenu: "افتح قائمة التنقل",
    closeMenu: "أغلق قائمة التنقل",
    closeDialog: "إغلاق",
    themeToDark: "التبديل إلى المظهر الداكن",
    themeToLight: "التبديل إلى المظهر الفاتح",
    languageSwitch: "اللغة",
    currentWorkspace: "مساحة العمل الحالية",
    liveConnecting: "جارٍ الاتصال",
    liveConnected: "مباشر",
    liveUnavailable: "المباشر غير متاح",
    liveReconnecting: "إعادة الاتصال",
    liveRefused: "تحقّق من الصلاحية",
    newBooking: "حجز جديد",
    todayWindow:
      "النطاق: اليوم الكامل بتوقيت الموقع الافتراضي، وتظهر أوقات المواعيد بتوقيت مواقعها.",
    timeZoneLabel: "المنطقة الزمنية",
    scheduleTitle: "جدول اليوم",
    scheduleLabel: "حجوزات {date}، شريط لكل عضو في الفريق",
    scheduleEmptyLane: "لا حجوزات",
    scheduleEmptyDay: "لا توجد مواعيد اليوم. الحجوزات القادمة معروضة أدناه.",
    scheduleUnassigned: "غير مُسند",
    scheduleUnknownMember: "عضو في الفريق",
    scheduleUnknownResource: "مورد",
    agendaLabel: "حجوزات اليوم مرتبة حسب الوقت",
    requestsColumnTitle: "بانتظار القرار",
    requestsColumnEmpty: "لا توجد طلبات بانتظار القرار.",
    reviewRequest: "مراجعة الطلب",
    reviewPayment: "مراجعة الدفع",
    reviewCommunications: "مراجعة الرسائل",
    nowAt: "الآن: {time}",
    foldLabel: "أيّ الوقتين عند تكرار الساعة المحلية",
    foldNone: "الوقت غير مكرر",
    foldFirst: "الوقت الأول",
    foldSecond: "الوقت الثاني",
    calendarHour: "الساعة",
    calendarTimetable: "الجدول الزمني للتقويم",
    calendarTimetableCaption: "أوقات البدء بالمنطقة الزمنية المختارة",
    calendarNoResource: "دون مورد مخصص",
    calendarResourceLabel: "حجوزات {date}، شريط لكل مورد",
    relatedPages: "صفحات مرتبطة",
    bookingChange: "تغيير في الحجز",
    actorStaff: "موظف",
    actorGuest: "العميل",
    actorSystem: "النظام",
    actorWorker: "معالج النظام الخلفي",
    actorUnknown: "جهة التنفيذ",
    reportsLocation: "الموقع",
    reportsAllLocations: "كل المواقع المتاحة لك",
    jobExport: "تصدير البيانات",
    jobDeletion: "الحذف",
    jobKind: "الطلب",
    refundAttempts: "المحاولات",
    utilizationMember: "عضو الفريق",
    utilizationMinutes: "الدقائق المحجوزة / المتاحة",
    refundFailure: "رمز الإخفاق",
    jobCreated: "تاريخ الفتح",
    jobProgress: "التقدّم",
    noteSensitivityLabel: "مستوى الظهور",
    filtersLabel: "عوامل التصفية",
    pendingRequestsBadge: "طلبات معلّقة",
    workspaceSwitcherHint: "عضوياتك",
    reference: "المرجع",
    service: "الخدمة",
    customer: "العميل",
    actions: "الإجراءات",
    rescheduleOrCancel: "إعادة الجدولة أو الإلغاء أو إعادة الإرسال",
    lifecycleActions: "إجراءات حالة الحجز",
    exportReveal: "محتوى التصدير",
    notFoundCode: "خطأ ٤٠٤",
    signOutLabel: "تسجيل الخروج",
    timesShownIn: "المنطقة الزمنية لهذه الصفحة",
    datePlaceholder: "اختر تاريخًا",
    timePlaceholder: "اختر وقتًا",
    timeOf: "{label}، الوقت",
  },
} as const satisfies Record<Locale, Record<string, string>>;

export type WorkspaceCopyKey = keyof typeof workspaceCopy.en;

export function workspaceMessage(
  locale: Locale,
  key: WorkspaceCopyKey,
  values?: Readonly<Record<string, string>>,
): string {
  const message: string = workspaceCopy[locale][key];
  if (values === undefined) return message;
  return message.replace(/\{(\w+)\}/gu, (match, name: string) =>
    Object.hasOwn(values, name) ? values[name]! : match,
  );
}

/*
 * Counted nouns. Arabic needs all six CLDR categories to read naturally
 * ("ملاحظتان", "٣ ملاحظات", "١١ ملاحظة"), so every Arabic entry supplies them.
 */
export const workspacePlurals = {
  en: {
    items: { one: "{count} item", other: "{count} items" },
    notes: { one: "{count} note", other: "{count} notes" },
    attempts: { one: "{count} attempt", other: "{count} attempts" },
    openSteps: { one: "{count} step still open", other: "{count} steps still open" },
    bookings: { one: "{count} booking", other: "{count} bookings" },
    minutes: { one: "{count} minute", other: "{count} minutes" },
    requests: {
      one: "{count} request awaiting a decision",
      other: "{count} requests awaiting a decision",
    },
    rows: { one: "{count} row", other: "{count} rows" },
    reschedules: { one: "{count} reschedule", other: "{count} reschedules" },
    records: { one: "{count} record", other: "{count} records" },
  },
  ar: {
    items: {
      zero: "لا عناصر",
      one: "عنصر واحد",
      two: "عنصران",
      few: "{count} عناصر",
      many: "{count} عنصرًا",
      other: "{count} عنصر",
    },
    notes: {
      zero: "لا ملاحظات",
      one: "ملاحظة واحدة",
      two: "ملاحظتان",
      few: "{count} ملاحظات",
      many: "{count} ملاحظة",
      other: "{count} ملاحظة",
    },
    attempts: {
      zero: "لا محاولات",
      one: "محاولة واحدة",
      two: "محاولتان",
      few: "{count} محاولات",
      many: "{count} محاولة",
      other: "{count} محاولة",
    },
    openSteps: {
      zero: "لا خطوات مفتوحة",
      one: "خطوة واحدة ما زالت مفتوحة",
      two: "خطوتان ما زالتا مفتوحتين",
      few: "{count} خطوات ما زالت مفتوحة",
      many: "{count} خطوة ما زالت مفتوحة",
      other: "{count} خطوة ما زالت مفتوحة",
    },
    bookings: {
      zero: "لا حجوزات",
      one: "حجز واحد",
      two: "حجزان",
      few: "{count} حجوزات",
      many: "{count} حجزًا",
      other: "{count} حجز",
    },
    minutes: {
      zero: "لا دقائق",
      one: "دقيقة واحدة",
      two: "دقيقتان",
      few: "{count} دقائق",
      many: "{count} دقيقة",
      other: "{count} دقيقة",
    },
    requests: {
      zero: "لا طلبات بانتظار القرار",
      one: "طلب واحد بانتظار القرار",
      two: "طلبان بانتظار القرار",
      few: "{count} طلبات بانتظار القرار",
      many: "{count} طلبًا بانتظار القرار",
      other: "{count} طلب بانتظار القرار",
    },
    rows: {
      zero: "لا صفوف",
      one: "صف واحد",
      two: "صفّان",
      few: "{count} صفوف",
      many: "{count} صفًا",
      other: "{count} صف",
    },
    reschedules: {
      zero: "لم يُعَد جدولته",
      one: "إعادة جدولة واحدة",
      two: "إعادتا جدولة",
      few: "{count} إعادات جدولة",
      many: "{count} إعادة جدولة",
      other: "{count} إعادة جدولة",
    },
    records: {
      zero: "لا سجلات",
      one: "سجل واحد",
      two: "سجلان",
      few: "{count} سجلات",
      many: "{count} سجلًا",
      other: "{count} سجل",
    },
  },
} as const satisfies Record<Locale, Record<string, PluralForms>>;

export type WorkspacePluralKey = keyof typeof workspacePlurals.en;

/** "3 items" / "٣ عناصر", chosen by Intl.PluralRules for the locale. */
export function countLabel(
  locale: Locale,
  key: WorkspacePluralKey,
  count: number,
): string {
  return formatPlural(count, locale, workspacePlurals[locale][key]);
}
