// GENERATED by scripts/bundle-edge-shared.mjs from packages/email/src/delivery.ts.
// Do not edit. Change the package and run `pnpm bundle:edge`.
import {
  NotificationPreparationError,
  type ClaimedNotification,
  type NotificationDelivery,
  type NotificationPorts,
} from "./worker.ts";

export interface NotificationPreparationOptions {
  readonly encryptionKey: string;
  readonly from: string;
  readonly replyTo?: string;
  readonly envelope: (
    message: ClaimedNotification,
    encryptedPayload: string | null,
  ) => Promise<string | null>;
  readonly mintOtp: (message: ClaimedNotification) => Promise<string>;
}

export function createNotificationPreparation(
  options: NotificationPreparationOptions,
): NonNullable<NotificationPorts["prepare"]> {
  if (!/^[a-f0-9]{64}$/iu.test(options.encryptionKey)) {
    throw new Error("notification_encryption_key_invalid");
  }
  const keyBytes = Uint8Array.from(
    options.encryptionKey.match(/.{2}/gu) ?? [],
    (pair) => Number.parseInt(pair, 16),
  );
  const key = crypto.subtle.importKey("raw", keyBytes, "AES-GCM", false, [
    "encrypt",
    "decrypt",
  ]);
  const decode = async (message: ClaimedNotification, envelope: string) => {
    const bytes = Uint8Array.from(atob(envelope), (character) =>
      character.charCodeAt(0),
    );
    const plaintext = await crypto.subtle.decrypt(
      {
        name: "AES-GCM",
        iv: bytes.slice(0, 12),
        additionalData: new TextEncoder().encode(
          `${message.tenantId}:${message.messageId}`,
        ),
      },
      await key,
      bytes.slice(12),
    );
    return JSON.parse(new TextDecoder().decode(plaintext)) as NotificationDelivery;
  };
  return async (message, render) => {
    try {
      const cached = await options.envelope(message, null);
      if (cached !== null) return await decode(message, cached);
    } catch {
      throw new NotificationPreparationError("delivery_preparation_failed");
    }
    let variables: Readonly<Record<string, string>> = {};
    if (message.templateKey === "management.otp_requested" && message.isTest !== true) {
      try {
        const code = await options.mintOtp(message);
        if (!/^\d{6}$/u.test(code)) throw new Error("notification_otp_invalid");
        variables = { code };
      } catch {
        throw new NotificationPreparationError("otp_preparation_failed");
      }
    }
    const delivery: NotificationDelivery = {
      ...(await render(variables)),
      from: options.from,
      replyTo: options.replyTo ?? "",
    };
    try {
      const nonce = crypto.getRandomValues(new Uint8Array(12));
      const encrypted = new Uint8Array(
        await crypto.subtle.encrypt(
          {
            name: "AES-GCM",
            iv: nonce,
            additionalData: new TextEncoder().encode(
              `${message.tenantId}:${message.messageId}`,
            ),
          },
          await key,
          new TextEncoder().encode(JSON.stringify(delivery)),
        ),
      );
      const bytes = new Uint8Array(nonce.length + encrypted.length);
      bytes.set(nonce);
      bytes.set(encrypted, nonce.length);
      let binary = "";
      for (const byte of bytes) binary += String.fromCharCode(byte);
      const stored = await options.envelope(message, btoa(binary));
      if (stored === null) throw new Error("notification_envelope_missing");
      return await decode(message, stored);
    } catch {
      throw new NotificationPreparationError("delivery_preparation_failed");
    }
  };
}
