// GENERATED by scripts/bundle-edge-shared.mjs from packages/email/src/digest.ts.
// Do not edit. Change the package and run `pnpm bundle:edge`.
import type { ContractLocale } from "./contracts.ts";

/**
 * Staff daily agenda. The database decides who receives a digest and when
 * (opted-in members, at their location's local time) and hands the worker raw
 * rows; this module turns those rows into the day as a person reads it — the
 * right day, in the location's own time zone, in start order, grouped by
 * location — so that logic is unit tested rather than buried in SQL.
 */
export interface DigestBookingInput {
  /** UTC instant, ISO 8601. */
  readonly startsAt: string;
  readonly serviceName: string;
  /** IANA zone of the booking's location. */
  readonly timeZone: string;
  readonly customerFirstName?: string;
  readonly locationName?: string;
  readonly staffName?: string;
}

export interface DigestEntry {
  readonly time: string;
  readonly serviceName: string;
  readonly customerFirstName?: string;
  readonly staffName?: string;
}

export interface DigestGroup {
  readonly locationName?: string;
  readonly entries: readonly DigestEntry[];
}

export interface DailyDigest {
  readonly count: number;
  readonly countLabel: string;
  readonly dateLabel: string;
  readonly groups: readonly DigestGroup[];
  /** Bookings beyond the display limit; the Dashboard link shows them all. */
  readonly hiddenCount: number;
  readonly showStaff: boolean;
  readonly timeZone: string;
}

export interface DailyDigestInput {
  readonly bookings: readonly DigestBookingInput[];
  readonly locale: ContractLocale;
  /** The recipient's local calendar day, `YYYY-MM-DD`. */
  readonly localDate: string;
  /** The recipient's location time zone. */
  readonly timeZone: string;
  readonly limit?: number;
}

const defaultLimit = 40;

function isValidTimeZone(zone: string): boolean {
  try {
    new Intl.DateTimeFormat("en", { timeZone: zone });
    return true;
  } catch {
    return false;
  }
}

function localDateOf(instant: Date, timeZone: string): string {
  // en-CA formats as YYYY-MM-DD, which is exactly the comparison key.
  return new Intl.DateTimeFormat("en-CA", {
    day: "2-digit",
    month: "2-digit",
    timeZone,
    year: "numeric",
  }).format(instant);
}

/** Only a first name ever reaches staff mail, however much the row carried. */
export function firstNameOnly(value: string | undefined): string | undefined {
  const first = value?.trim().split(/\s+/u)[0]?.slice(0, 40);
  return first === undefined || first === "" ? undefined : first;
}

const arabicCount: Record<Intl.LDMLPluralRule, (n: string) => string> = {
  few: (n) => `${n} حجوزات`,
  many: (n) => `${n} حجزًا`,
  one: () => "حجز واحد",
  other: (n) => `${n} حجز`,
  two: () => "حجزان",
  zero: () => "لا توجد حجوزات",
};

export function formatBookingCount(count: number, locale: ContractLocale): string {
  const number = new Intl.NumberFormat(locale).format(count);
  if (locale === "ar") {
    const rule = new Intl.PluralRules("ar").select(count);
    return arabicCount[rule](number);
  }
  if (count === 0) return "No bookings";
  return count === 1 ? "1 booking" : `${number} bookings`;
}

export function formatDigestDate(localDate: string, locale: ContractLocale): string {
  if (!/^\d{4}-\d{2}-\d{2}$/u.test(localDate)) return localDate;
  const noon = new Date(`${localDate}T12:00:00.000Z`);
  if (Number.isNaN(noon.getTime())) return localDate;
  return new Intl.DateTimeFormat(locale, {
    day: "numeric",
    month: "long",
    timeZone: "UTC",
    weekday: "long",
  }).format(noon);
}

export function buildDailyDigest(input: DailyDigestInput): DailyDigest {
  const fallbackZone = isValidTimeZone(input.timeZone) ? input.timeZone : "UTC";
  const limit = Math.max(1, input.limit ?? defaultLimit);

  const rows = input.bookings
    .map((booking) => {
      const instant = new Date(booking.startsAt);
      const zone = isValidTimeZone(booking.timeZone) ? booking.timeZone : fallbackZone;
      return { booking, instant, zone };
    })
    .filter(
      ({ booking, instant, zone }) =>
        !Number.isNaN(instant.getTime()) &&
        booking.serviceName.trim() !== "" &&
        localDateOf(instant, zone) === input.localDate,
    )
    .sort(
      (a, b) =>
        a.instant.getTime() - b.instant.getTime() ||
        a.booking.serviceName.localeCompare(b.booking.serviceName),
    );

  const shown = rows.slice(0, limit);
  const groups = new Map<string, DigestEntry[]>();
  const names = new Map<string, string | undefined>();
  for (const { booking, instant, zone } of shown) {
    const locationName = booking.locationName?.trim() || undefined;
    const key = locationName ?? "";
    const customerFirstName = firstNameOnly(booking.customerFirstName);
    const staffName = booking.staffName?.trim() || undefined;
    const entry: DigestEntry = {
      serviceName: booking.serviceName.trim(),
      time: new Intl.DateTimeFormat(input.locale, {
        hour: "numeric",
        minute: "2-digit",
        timeZone: zone,
      }).format(instant),
      ...(customerFirstName === undefined ? {} : { customerFirstName }),
      ...(staffName === undefined ? {} : { staffName }),
    };
    const list = groups.get(key);
    if (list === undefined) {
      groups.set(key, [entry]);
      names.set(key, locationName);
    } else {
      list.push(entry);
    }
  }

  return {
    count: rows.length,
    countLabel: formatBookingCount(rows.length, input.locale),
    dateLabel: formatDigestDate(input.localDate, input.locale),
    groups: [...groups].map(([key, entries]) => {
      const locationName = names.get(key);
      return locationName === undefined ? { entries } : { entries, locationName };
    }),
    hiddenCount: rows.length - shown.length,
    showStaff: shown.some(({ booking }) => (booking.staffName?.trim() ?? "") !== ""),
    timeZone: fallbackZone,
  };
}
