// GENERATED by scripts/bundle-edge-shared.mjs from packages/email/src/intl-locale.ts.
// Do not edit. Change the package and run `pnpm bundle:edge`.
/** Display locale for Intl: Arabic uses Arabic-Indic digits, matching every app. */
export function intlLocale(locale: string): string {
  return locale === "ar" || locale.startsWith("ar-") ? "ar-u-nu-arab" : locale;
}
