// GENERATED by scripts/bundle-edge-shared.mjs from packages/email/src/samples.ts.
// Do not edit. Change the package and run `pnpm bundle:edge`.
import { intlLocale } from "./intl-locale.ts";
import type { ContractLocale } from "./contracts.ts";

import { buildDailyDigest, type DailyDigest } from "./digest.ts";
import { formatInstant, formatLead } from "./payload.ts";
import type { NotificationTemplateKey } from "./templates.ts";

/**
 * Fixed, obviously synthetic sample data for the Dashboard email preview. No
 * real customer, booking or link ever appears in a preview: names say
 * "sample", references say SAMPLE, and every link points at the reserved
 * `example.invalid` domain. Only the brand around it is the tenant's own.
 */
export interface PreviewSample {
  readonly digest?: DailyDigest;
  readonly variables: Readonly<Record<string, string>>;
}

const sampleZone = "Asia/Riyadh";
const sampleStart = "2026-03-15T10:30:00.000Z";
const sampleProposal = "2026-03-16T13:00:00.000Z";
const sampleDeadline = "2026-03-14T18:00:00.000Z";
const sampleDate = "2026-03-15";

const words: Record<
  ContractLocale,
  {
    readonly address: string;
    readonly customers: readonly string[];
    readonly location: string;
    readonly reason: string;
    readonly services: readonly string[];
    readonly staff: string;
  }
> = {
  ar: {
    address: "شارع المثال، الرياض",
    customers: ["مثال", "تجربة", "عينة"],
    location: "الفرع التجريبي",
    reason: "هذا نص تجريبي يوضح مكان السبب الذي يظهر للعميل.",
    services: ["خدمة تجريبية", "خدمة تجريبية ثانية", "خدمة تجريبية ثالثة"],
    staff: "موظف تجريبي",
  },
  en: {
    address: "Example Street, Riyadh",
    customers: ["Example", "Sample", "Test"],
    location: "Sample location",
    reason:
      "This is sample text showing where the reason given to the customer appears.",
    services: ["Sample service", "Second sample service", "Third sample service"],
    staff: "Sample staff member",
  },
};

function money(locale: ContractLocale): string {
  return new Intl.NumberFormat(intlLocale(locale), {
    currency: "SAR",
    style: "currency",
  }).format(180);
}

export function notificationPreviewSample(
  key: NotificationTemplateKey,
  locale: ContractLocale,
): PreviewSample {
  const copy = words[locale];
  const formatted = (iso: string) => formatInstant(iso, sampleZone, locale) ?? iso;
  const variables: Record<string, string> = {
    actionUrl: "https://example.invalid/auth/sample",
    code: "123456",
    decisionDeadline: formatted(sampleDeadline),
    expiresAt: new Intl.DateTimeFormat(intlLocale(locale), {
      hour: "numeric",
      minute: "2-digit",
      timeZone: sampleZone,
    }).format(new Date(sampleStart)),
    leadLabel: formatLead(1440, locale) ?? "",
    locationAddress: copy.address,
    locationName: copy.location,
    manageUrl: "https://example.invalid/manage/sample",
    price: money(locale),
    proposalUrl: "https://example.invalid/proposal/sample",
    proposedStartAt: formatted(sampleProposal),
    publicReason: copy.reason,
    publicReference: "SAMPLE0000",
    refund: money(locale),
    serviceName: copy.services[0] ?? "",
    staffName: copy.staff,
    startAt: formatted(sampleStart),
    timeZone: sampleZone,
  };

  if (key !== "staff.daily_digest") return { variables };
  const startTimes = [
    "2026-03-15T06:00:00.000Z",
    "2026-03-15T08:30:00.000Z",
    sampleStart,
  ];
  return {
    digest: buildDailyDigest({
      bookings: startTimes.map((startsAt, index) => ({
        customerFirstName: copy.customers[index] ?? "",
        serviceName: copy.services[index] ?? "",
        staffName: copy.staff,
        startsAt,
        timeZone: sampleZone,
      })),
      locale,
      localDate: sampleDate,
      timeZone: sampleZone,
    }),
    variables,
  };
}
