/**
 * Tenant custom roles (ADR-0019). The database is the authority for every rule
 * here: reserved permissions, built-in locking, scope/mode consistency and
 * dominance (no escalation) are enforced by `save_role_v1`, `archive_role_v1`
 * and `change_staff_access_v1`. The pure functions in this module mirror those
 * rules only so the Dashboard can disable choices the server would refuse.
 */
import {
  capabilityKeyPattern,
  isKnownCapability,
  type CapabilityName,
} from "./capabilities.js";

export const builtInRoleKeys = [
  "staff",
  "scheduler",
  "location_manager",
  "tenant_admin",
] as const;
export type BuiltInRoleKey = (typeof builtInRoleKeys)[number];

/** Custom role keys are generated by the server, never chosen by a person. */
export const customRoleKeyPattern = /^custom_[0-9a-f]{16}$/u;

export const grantKindsV1 = ["direct", "approval"] as const;
export type GrantKindV1 = (typeof grantKindsV1)[number];

export const grantScopesV1 = ["tenant", "location", "own"] as const;
export type GrantScopeV1 = (typeof grantScopesV1)[number];

export const roleModesV1 = ["tenant", "assigned"] as const;
/** `tenant`: every location. `assigned`: only the member's location rows. */
export type RoleModeV1 = (typeof roleModesV1)[number];

/**
 * Owner-level permissions. Only built-in roles may hold them; a custom role
 * carrying one is refused (`reserved_permission`).
 */
export const reservedPermissionKeysV1 = [
  "role.manage",
  "billing.view",
  "billing.change_plan",
  "support.grant_access",
  "tenant.owner_transfer",
  "tenant.read_other_tenant",
] as const satisfies readonly CapabilityName[];

export function isReservedPermissionV1(key: string): boolean {
  return (reservedPermissionKeysV1 as readonly string[]).includes(key);
}

export const roleNameMaxLengthV1 = 80;
export const roleDescriptionMaxLengthV1 = 500;
export const roleGrantLimitV1 = 32;

export const permissionGroupsV1 = [
  "bookings",
  "catalog_schedule",
  "team",
  "customers_privacy",
  "brand_integrations",
  "audit",
  "owner",
  /** A group added by a newer backend that this release cannot place. */
  "other",
] as const;
export type PermissionGroupV1 = (typeof permissionGroupsV1)[number];

export interface PermissionMetaV1 {
  readonly key: CapabilityName;
  readonly group: PermissionGroupV1;
  readonly allowedScopes: readonly GrantScopeV1[];
  readonly allowedGrantKinds: readonly GrantKindV1[];
  readonly reserved: boolean;
  readonly sortOrder: number;
}

export interface RoleCatalogV1 {
  readonly tenantId: string;
  readonly permissions: readonly PermissionMetaV1[];
}

export interface RoleGrantV1 {
  readonly permissionKey: CapabilityName;
  readonly grantKind: GrantKindV1;
  readonly scope: GrantScopeV1;
}
export type RoleGrantInputV1 = RoleGrantV1;

interface RoleBaseV1 {
  readonly id: string;
  readonly mode: RoleModeV1;
  readonly revision: number;
  readonly archived: boolean;
  readonly archivedAt: string | null;
  readonly updatedAt: string;
  readonly duplicatedFromRoleId: string | null;
  readonly administrator: boolean;
  readonly activeMembers: number;
  readonly pendingInvitations: number;
  /** Server-computed: the current actor dominates this role's grants. */
  readonly assignable: boolean;
  readonly grants: readonly RoleGrantV1[];
  /**
   * The role holds permissions this release does not know. Editing it here
   * would silently drop them, so the editor must refuse until it is updated.
   */
  readonly hasUnknownGrants: boolean;
}

export interface BuiltInRoleV1 extends RoleBaseV1 {
  readonly kind: "builtin";
  readonly key: BuiltInRoleKey;
}

export interface CustomRoleV1 extends RoleBaseV1 {
  readonly kind: "custom";
  readonly key: string;
  readonly nameEn: string;
  readonly nameAr: string;
  readonly descriptionEn: string | null;
  readonly descriptionAr: string | null;
}

export type RoleV1 = BuiltInRoleV1 | CustomRoleV1;

export interface RolesV1 {
  readonly tenantId: string;
  readonly canManageRoles: boolean;
  readonly roles: readonly RoleV1[];
}

export type SaveRoleActionV1 = "create" | "duplicate" | "update";

export interface SaveRoleResultV1 {
  readonly roleId: string;
  readonly key: string;
  readonly revision: number;
  readonly action: SaveRoleActionV1;
  readonly replayed: boolean;
}

export interface ArchiveRoleResultV1 {
  readonly roleId: string;
  readonly key: string;
  readonly revision: number;
  readonly action: "archive";
  readonly replayed: boolean;
}

/** Exception messages raised by the role RPCs (see docs/roles.md). */
export const roleMutationErrorCodesV1 = [
  "role_locked",
  "revision_conflict",
  "idempotency_conflict",
  "role_in_use",
  "role_scope_in_use",
  "permission_reserved",
  "escalation_denied",
  "step_up_required",
  "grant_not_allowed",
  "scope_mode_mismatch",
  "role_archived",
  "role_name_taken",
  "role_key_immutable",
  "last_administrator_required",
  "invitation_not_pending",
  "invitation_unavailable",
  "member_already_active",
  "invalid_request",
  "not_authorized",
] as const;
export type RoleMutationErrorCodeV1 = (typeof roleMutationErrorCodesV1)[number];

export interface RoleMutationErrorV1 {
  readonly code: RoleMutationErrorCodeV1;
  /** Present for `role_in_use` / `role_scope_in_use` when the server reports it. */
  readonly members?: number;
  readonly invitations?: number;
}

// ---------------------------------------------------------------------------
// Pure rules mirrored from SQL (private.grant_covers / actor_dominates_grants)

const scopeRank: Readonly<Record<GrantScopeV1, number>> = {
  tenant: 3,
  location: 2,
  own: 1,
};

/**
 * Whether one actor grant lets the actor hand out one target grant: same
 * permission, scope at least as wide (tenant > location > own), and a direct
 * grant covers direct or approval while an approval grant covers approval only.
 */
export function grantCovers(actor: RoleGrantV1, target: RoleGrantV1): boolean {
  return (
    actor.permissionKey === target.permissionKey &&
    scopeRank[actor.scope] >= scopeRank[target.scope] &&
    (actor.grantKind === "direct" || target.grantKind === "approval")
  );
}

export interface GrantActorV1 {
  readonly grants: readonly RoleGrantV1[];
  /** `all` for a tenant-mode role; otherwise the actor's assigned locations. */
  readonly locationIds: readonly string[] | "all";
}

export interface GrantTargetV1 {
  readonly grants: readonly RoleGrantV1[];
  /**
   * Locations the target member will hold. `null` is a role-level check (role
   * editor, `assignable`): location containment is then checked at assignment.
   */
  readonly locationIds: readonly string[] | null;
}

function locationsContained(
  actor: GrantActorV1["locationIds"],
  target: GrantTargetV1["locationIds"],
): boolean {
  if (actor === "all" || target === null) return true;
  return target.every((locationId) => actor.includes(locationId));
}

/** Whether the actor may grant this single grant to the target locations. */
export function actorCanGrant(
  actor: GrantActorV1,
  grant: RoleGrantV1,
  targetLocationIds: GrantTargetV1["locationIds"] = null,
): boolean {
  return actor.grants.some(
    (held) =>
      grantCovers(held, grant) &&
      (held.scope === "tenant" ||
        locationsContained(actor.locationIds, targetLocationIds)),
  );
}

/** Target grants the actor cannot hand out; empty means the actor dominates. */
export function uncoveredGrants(
  actor: GrantActorV1,
  target: GrantTargetV1,
): readonly RoleGrantV1[] {
  return target.grants.filter(
    (grant) => !actorCanGrant(actor, grant, target.locationIds),
  );
}

export function dominates(actor: GrantActorV1, target: GrantTargetV1): boolean {
  return uncoveredGrants(actor, target).length === 0;
}

/** Tenant-mode roles carry no location grants; assigned roles no tenant grants. */
export function grantScopeAllowedInMode(
  mode: RoleModeV1,
  scope: GrantScopeV1,
): boolean {
  return mode === "tenant" ? scope !== "location" : scope !== "tenant";
}

export type RoleGrantIssueCodeV1 =
  | "empty"
  | "too_many"
  | "duplicate"
  | "reserved"
  | "unknown_permission"
  | "scope_not_allowed"
  | "grant_kind_not_allowed"
  | "scope_mode_mismatch";

export interface RoleGrantIssueV1 {
  readonly code: RoleGrantIssueCodeV1;
  readonly permissionKey?: string;
}

/**
 * Validates a custom role draft the way `save_role_v1` does (minus dominance,
 * which needs the actor). With a catalog, keys and allowed scope/kind are
 * checked against it too.
 */
export function validateCustomRoleGrantsV1(
  mode: RoleModeV1,
  grants: readonly RoleGrantInputV1[],
  catalog?: readonly PermissionMetaV1[],
): readonly RoleGrantIssueV1[] {
  const issues: RoleGrantIssueV1[] = [];
  if (grants.length === 0) issues.push({ code: "empty" });
  if (grants.length > roleGrantLimitV1) issues.push({ code: "too_many" });
  const seen = new Set<string>();
  for (const grant of grants) {
    const permissionKey = grant.permissionKey;
    if (seen.has(permissionKey)) issues.push({ code: "duplicate", permissionKey });
    seen.add(permissionKey);
    const meta = catalog?.find((item) => item.key === permissionKey);
    if (isReservedPermissionV1(permissionKey) || meta?.reserved === true) {
      issues.push({ code: "reserved", permissionKey });
      continue;
    }
    if (catalog && !meta) {
      issues.push({ code: "unknown_permission", permissionKey });
      continue;
    }
    if (meta && !meta.allowedScopes.includes(grant.scope))
      issues.push({ code: "scope_not_allowed", permissionKey });
    if (meta && !meta.allowedGrantKinds.includes(grant.grantKind))
      issues.push({ code: "grant_kind_not_allowed", permissionKey });
    if (!grantScopeAllowedInMode(mode, grant.scope))
      issues.push({ code: "scope_mode_mismatch", permissionKey });
  }
  return issues;
}

// ---------------------------------------------------------------------------
// Parsers (snake_case database JSON → camelCase DTOs; exact keys, fail closed)

function fail(what: string): never {
  throw new Error(`Invalid role contract: ${what}`);
}

function object(value: unknown, what: string, keys: readonly string[]) {
  if (typeof value !== "object" || value === null || Array.isArray(value)) fail(what);
  const row = value as Record<string, unknown>;
  const actual = Object.keys(row).sort();
  const expected = [...keys].sort();
  if (
    actual.length !== expected.length ||
    actual.some((key, index) => key !== expected[index])
  )
    fail(`${what} keys`);
  return row;
}

function versioned(value: unknown, what: string, keys: readonly string[]) {
  const row = object(value, what, ["version", ...keys]);
  if (row.version !== 1) fail(`${what} version`);
  return row;
}

const uuidPattern = /^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/iu;

function id(value: unknown, what: string): string {
  if (typeof value !== "string" || !uuidPattern.test(value)) fail(what);
  return value;
}

function count(value: unknown, what: string, min = 0): number {
  if (typeof value !== "number" || !Number.isSafeInteger(value) || value < min)
    fail(what);
  return value;
}

function bool(value: unknown, what: string): boolean {
  if (typeof value !== "boolean") fail(what);
  return value;
}

function timestamp(value: unknown, what: string): string {
  if (
    typeof value !== "string" ||
    value.length > 64 ||
    !Number.isFinite(Date.parse(value))
  )
    fail(what);
  return value;
}

function nullable<T>(value: unknown, parse: (value: unknown) => T): T | null {
  return value === null ? null : parse(value);
}

function label(value: unknown, what: string, max: number): string {
  if (typeof value !== "string" || value.trim() === "" || value.length > max)
    fail(what);
  return value;
}

function choice<T extends string>(
  value: unknown,
  choices: readonly T[],
  what: string,
): T {
  if (typeof value !== "string" || !(choices as readonly string[]).includes(value))
    fail(what);
  return value as T;
}

function list(value: unknown, what: string, max: number): unknown[] {
  if (!Array.isArray(value) || value.length > max) fail(what);
  return value;
}

function uniqueChoices<T extends string>(
  value: unknown,
  choices: readonly T[],
  what: string,
): readonly T[] {
  const result = list(value, what, choices.length).map((item) =>
    choice(item, choices, what),
  );
  if (result.length === 0 || new Set(result).size !== result.length) fail(what);
  return result;
}

/** `null` when well-formed but unknown to this release (N-1 tolerance). */
function permissionKey(value: unknown): CapabilityName | null {
  if (typeof value !== "string" || !capabilityKeyPattern.test(value))
    fail("permission key");
  return isKnownCapability(value) ? value : null;
}

export function parseRoleCatalogV1(value: unknown): RoleCatalogV1 {
  const row = versioned(value, "catalog", ["tenant_id", "permissions"]);
  const permissions: PermissionMetaV1[] = [];
  for (const item of list(row.permissions, "permissions", 256)) {
    const meta = object(item, "permission", [
      "key",
      "group",
      "allowed_scopes",
      "allowed_grant_kinds",
      "reserved",
      "sort_order",
    ]);
    const key = permissionKey(meta.key);
    if (typeof meta.group !== "string" || !/^[a-z][a-z_]*$/u.test(meta.group))
      fail("permission group");
    const parsed = {
      group: (permissionGroupsV1 as readonly string[]).includes(meta.group)
        ? (meta.group as PermissionGroupV1)
        : "other",
      allowedScopes: uniqueChoices(
        meta.allowed_scopes,
        grantScopesV1,
        "allowed scopes",
      ),
      allowedGrantKinds: uniqueChoices(
        meta.allowed_grant_kinds,
        grantKindsV1,
        "allowed grant kinds",
      ),
      reserved: bool(meta.reserved, "reserved"),
      sortOrder: count(meta.sort_order, "sort order"),
    } as const;
    if (key === null) continue;
    if (permissions.some((existing) => existing.key === key))
      fail("duplicate permission");
    // Conservative union: the local reserved list can only add restrictions.
    permissions.push({
      key,
      ...parsed,
      reserved: parsed.reserved || isReservedPermissionV1(key),
    });
  }
  return { tenantId: id(row.tenant_id, "tenant"), permissions };
}

function parseGrants(value: unknown, mode: RoleModeV1, builtIn: boolean) {
  const grants: RoleGrantV1[] = [];
  let hasUnknownGrants = false;
  for (const item of list(value, "grants", 256)) {
    const grant = object(item, "grant", ["permission_key", "grant_kind", "scope_kind"]);
    const key = permissionKey(grant.permission_key);
    const grantKind = choice(grant.grant_kind, grantKindsV1, "grant kind");
    const scope = choice(grant.scope_kind, grantScopesV1, "grant scope");
    if (!grantScopeAllowedInMode(mode, scope)) fail("grant scope for mode");
    if (key === null) {
      hasUnknownGrants = true;
      continue;
    }
    if (!builtIn && isReservedPermissionV1(key)) fail("reserved grant on custom role");
    if (grants.some((existing) => existing.permissionKey === key))
      fail("duplicate grant");
    grants.push({ permissionKey: key, grantKind, scope });
  }
  return { grants, hasUnknownGrants };
}

function parseRole(value: unknown): RoleV1 {
  const row = object(value, "role", [
    "id",
    "key",
    "is_builtin",
    "name_en",
    "name_ar",
    "description_en",
    "description_ar",
    "location_scope_mode",
    "revision",
    "archived",
    "archived_at",
    "updated_at",
    "duplicated_from_role_id",
    "administrator",
    "active_members",
    "pending_invitations",
    "assignable",
    "grants",
  ]);
  const isBuiltIn = bool(row.is_builtin, "is_builtin");
  const mode = choice(row.location_scope_mode, roleModesV1, "role mode");
  const base = {
    id: id(row.id, "role id"),
    mode,
    revision: count(row.revision, "role revision", 1),
    archived: bool(row.archived, "archived"),
    archivedAt: nullable(row.archived_at, (v) => timestamp(v, "archived_at")),
    updatedAt: timestamp(row.updated_at, "updated_at"),
    duplicatedFromRoleId: nullable(row.duplicated_from_role_id, (v) =>
      id(v, "duplicated_from_role_id"),
    ),
    administrator: bool(row.administrator, "administrator"),
    activeMembers: count(row.active_members, "active members"),
    pendingInvitations: count(row.pending_invitations, "pending invitations"),
    assignable: bool(row.assignable, "assignable"),
    ...parseGrants(row.grants, mode, isBuiltIn),
  };
  if (isBuiltIn) {
    const key = choice(row.key, builtInRoleKeys, "built-in role key");
    if (
      row.name_en !== null ||
      row.name_ar !== null ||
      row.description_en !== null ||
      row.description_ar !== null ||
      row.archived_at !== null ||
      row.duplicated_from_role_id !== null
    )
      fail("built-in role carries custom fields");
    if (row.archived !== false) fail("built-in role archived");
    return { kind: "builtin", key, ...base };
  }
  if (typeof row.key !== "string" || !customRoleKeyPattern.test(row.key))
    fail("custom role key");
  if (row.archived !== (row.archived_at !== null)) fail("archive state");
  return {
    kind: "custom",
    key: row.key,
    nameEn: label(row.name_en, "name_en", roleNameMaxLengthV1),
    nameAr: label(row.name_ar, "name_ar", roleNameMaxLengthV1),
    descriptionEn: nullable(row.description_en, (v) =>
      label(v, "description_en", roleDescriptionMaxLengthV1),
    ),
    descriptionAr: nullable(row.description_ar, (v) =>
      label(v, "description_ar", roleDescriptionMaxLengthV1),
    ),
    ...base,
  };
}

export function parseRolesV1(value: unknown): RolesV1 {
  const row = versioned(value, "roles", ["tenant_id", "can_manage_roles", "roles"]);
  const roles = list(row.roles, "roles", 1000).map(parseRole);
  if (new Set(roles.map((role) => role.id)).size !== roles.length)
    fail("duplicate role");
  return {
    tenantId: id(row.tenant_id, "tenant"),
    canManageRoles: bool(row.can_manage_roles, "can_manage_roles"),
    roles,
  };
}

export function parseSaveRoleResultV1(value: unknown): SaveRoleResultV1 {
  const row = versioned(value, "save result", [
    "role_id",
    "key",
    "revision",
    "action",
    "replayed",
  ]);
  return {
    roleId: id(row.role_id, "role id"),
    key: label(row.key, "role key", 80),
    revision: count(row.revision, "revision", 1),
    action: choice(row.action, ["create", "duplicate", "update"], "action"),
    replayed: bool(row.replayed, "replayed"),
  };
}

export function parseArchiveRoleResultV1(value: unknown): ArchiveRoleResultV1 {
  const row = versioned(value, "archive result", [
    "role_id",
    "key",
    "revision",
    "action",
    "replayed",
  ]);
  return {
    roleId: id(row.role_id, "role id"),
    key: label(row.key, "role key", 80),
    revision: count(row.revision, "revision", 1),
    action: choice(row.action, ["archive"], "action"),
    replayed: bool(row.replayed, "replayed"),
  };
}

/**
 * Maps a PostgREST error from a role RPC to a known code. The message must be
 * exactly the code; `role_in_use` / `role_scope_in_use` may carry
 * `{"members":n,"invitations":n}` as the error detail.
 */
export function parseRoleMutationErrorV1(error: unknown): RoleMutationErrorV1 | null {
  if (typeof error !== "object" || error === null) return null;
  const { message, details } = error as { message?: unknown; details?: unknown };
  if (typeof message !== "string") return null;
  const code = (roleMutationErrorCodesV1 as readonly string[]).find(
    (candidate) => candidate === message.trim(),
  ) as RoleMutationErrorCodeV1 | undefined;
  if (!code) return null;
  if (
    (code === "role_in_use" || code === "role_scope_in_use") &&
    typeof details === "string"
  ) {
    try {
      const parsed: unknown = JSON.parse(details);
      if (typeof parsed === "object" && parsed !== null) {
        const { members, invitations } = parsed as Record<string, unknown>;
        if (
          typeof members === "number" &&
          Number.isSafeInteger(members) &&
          members >= 0 &&
          typeof invitations === "number" &&
          Number.isSafeInteger(invitations) &&
          invitations >= 0
        )
          return { code, members, invitations };
      }
    } catch {
      // Detail is advisory; the code alone is still meaningful.
    }
  }
  return { code };
}

// ---------------------------------------------------------------------------
// Request builders

export interface SaveRoleV1Input {
  readonly tenantId: string;
  readonly requestId: string;
  /** `null` creates a role (optionally duplicated from `sourceRoleId`). */
  readonly roleId: string | null;
  readonly expectedRevision: number | null;
  readonly sourceRoleId: string | null;
  readonly nameEn: string;
  readonly nameAr: string;
  readonly descriptionEn: string | null;
  readonly descriptionAr: string | null;
  readonly mode: RoleModeV1;
  readonly grants: readonly RoleGrantInputV1[];
}

function optionalDescription(value: string | null, what: string): string | null {
  if (value === null) return null;
  const trimmed = value.trim();
  if (trimmed === "") return null;
  return label(trimmed, what, roleDescriptionMaxLengthV1);
}

export function buildSaveRoleV1Request(input: SaveRoleV1Input) {
  const creating = input.roleId === null;
  if (creating !== (input.expectedRevision === null)) fail("role id and revision");
  if (!creating && input.sourceRoleId !== null) fail("source role on update");
  for (const grant of input.grants)
    if (!isKnownCapability(grant.permissionKey)) fail("unknown permission");
  const [issue] = validateCustomRoleGrantsV1(input.mode, input.grants);
  if (issue) fail(`grants (${issue.code})`);
  return {
    p_tenant_id: id(input.tenantId, "tenant"),
    p_request_id: id(input.requestId, "request"),
    p_role_id: input.roleId === null ? null : id(input.roleId, "role id"),
    p_expected_revision:
      input.expectedRevision === null
        ? null
        : count(input.expectedRevision, "expected revision", 1),
    p_source_role_id:
      input.sourceRoleId === null ? null : id(input.sourceRoleId, "source role"),
    p_name_en: label(input.nameEn.trim(), "name_en", roleNameMaxLengthV1),
    p_name_ar: label(input.nameAr.trim(), "name_ar", roleNameMaxLengthV1),
    p_description_en: optionalDescription(input.descriptionEn, "description_en"),
    p_description_ar: optionalDescription(input.descriptionAr, "description_ar"),
    p_location_scope_mode: choice(input.mode, roleModesV1, "role mode"),
    p_grants: input.grants.map((grant) => ({
      permission_key: grant.permissionKey,
      grant_kind: choice(grant.grantKind, grantKindsV1, "grant kind"),
      scope_kind: choice(grant.scope, grantScopesV1, "grant scope"),
    })),
  };
}

export function buildArchiveRoleV1Request(input: {
  readonly tenantId: string;
  readonly requestId: string;
  readonly roleId: string;
  readonly expectedRevision: number;
}) {
  return {
    p_tenant_id: id(input.tenantId, "tenant"),
    p_request_id: id(input.requestId, "request"),
    p_role_id: id(input.roleId, "role id"),
    p_expected_revision: count(input.expectedRevision, "expected revision", 1),
  };
}
