// Issue #101. The entry point that actually sends a tenant's mail.
//
// It is a shell. Batching, rendering, provider classification and the retry
// decision all live in `packages/email`, unit tested with an injected transport
// and no network; what is left here is secrets, HTTP, and the ports that join
// the two. The vendored copy under `_shared/email` is generated by
// `pnpm bundle:edge`, because Deno cannot follow the package's Node specifiers.
//
// Nothing durable happens in this process. Claiming is a database call under a
// visibility timeout and recording an attempt is another, so a worker killed
// mid-batch loses nothing: the visibility timeout expires and the message is
// claimed again.
import { parseNotificationBrandRow } from "../_shared/email/brand.ts";
import {
  createResendAdapter,
  runNotificationBatch,
  type ClaimedNotification,
} from "../_shared/email/worker.ts";
import {
  callRpc,
  isInternalInvocation,
  json,
  platformConfigured,
  unauthorized,
  unconfigured,
} from "../_shared/rpc.ts";

const resendApiKey = Deno.env.get("RESEND_API_KEY") ?? "";
const sender = Deno.env.get("NOTIFICATION_SENDER") ?? "";
const replyTo = Deno.env.get("NOTIFICATION_REPLY_TO") ?? "";
const batchSize = Number(Deno.env.get("NOTIFICATION_BATCH_SIZE") ?? "20");
const visibilitySeconds = Number(
  Deno.env.get("NOTIFICATION_VISIBILITY_SECONDS") ?? "120",
);

interface ClaimedRow {
  readonly attempt: number;
  readonly booking_revision: number;
  readonly correlation_id: string;
  /** Set by `enqueue_test_notification_v1`; absent on older claim shapes. */
  readonly is_test?: boolean | null;
  readonly message_id: string;
  readonly payload: Record<string, unknown> | null;
  readonly recipient_email: string;
  readonly template_key: string;
  readonly template_locale: string;
  readonly tenant_id: string;
}

Deno.serve(async (request: Request): Promise<Response> => {
  if (!isInternalInvocation(request)) return unauthorized();
  if (!platformConfigured() || resendApiKey === "" || sender === "") {
    return unconfigured();
  }

  // Committed outbox intents become messages first. This is idempotent on the
  // intent key, so running the worker twice dispatches nothing twice.
  const dispatched = await callRpc<{ dispatched: number; suppressed: number }>(
    "dispatch_notifications_v1",
    { p_limit: Math.max(batchSize * 5, 100), p_tenant_id: null },
  );
  if (dispatched === null) return json({ error: "dispatch_failed" }, 500);

  const summary = await runNotificationBatch({
    claim: async () => {
      const rows = await callRpc<ClaimedRow>("claim_notification_batch_v1", {
        p_limit: batchSize,
        p_visibility_seconds: visibilitySeconds,
      });
      if (rows === null) return [];
      return rows.map((row): ClaimedNotification => ({
        attempt: row.attempt,
        bookingRevision: row.booking_revision,
        correlationId: row.correlation_id,
        ...(row.is_test === true ? { isTest: true } : {}),
        locale: row.template_locale === "ar" ? "ar" : "en",
        messageId: row.message_id,
        payload: row.payload ?? {},
        recipient: row.recipient_email,
        templateKey: row.template_key as ClaimedNotification["templateKey"],
        tenantId: row.tenant_id,
      }));
    },
    deliver: createResendAdapter({
      apiKey: resendApiKey,
      from: sender,
      ...(replyTo === "" ? {} : { replyTo }),
    }),
    record: async (input) => {
      // The only thing that decides whether sending is over. If this call
      // fails the message stays claimed until its visibility timeout expires
      // and is tried again, which is the safe direction.
      await callRpc("record_notification_attempt_v1", {
        p_attempt: input.attempt,
        p_error_code: input.report.errorCode ?? null,
        p_message_id: input.messageId,
        p_outcome: input.report.outcome,
        p_provider_reference: input.report.providerReference ?? null,
        p_started_at: input.startedAt,
      });
    },
    resolveBrand: async (tenantId) => {
      // The published brand revision plus verified hostnames. A failed lookup
      // is null, which the batch treats as "try again later" — never as a
      // reason to sign the message with a platform name.
      const rows = await callRpc<unknown>("get_notification_brand_v2", {
        p_tenant_id: tenantId,
      });
      return rows === null ? null : parseNotificationBrandRow(rows[0]);
    },
  });

  return json({ dispatched: dispatched[0] ?? null, ...summary });
});
