export const operatorsCopy = {
  title: ["Operators", "المشغّلون"],
  description: [
    "Who can use Platform Admin and at what level. Changes take effect on the person's next action.",
    "من يمكنه استخدام إدارة المنصة وبأي مستوى. تسري التغييرات مع الإجراء التالي للشخص.",
  ],
  roles: [
    "Viewer reads everything here. Operator also runs routine work (queue, retry, cancel, request support). Administrator also changes tenants, plans, releases, operators and settings. Break-glass is administrator access that expires within eight hours and must be granted by someone else.",
    "المشاهد يقرأ كل شيء هنا. المشغّل يضيف العمل الروتيني (جدولة، إعادة محاولة، إلغاء، طلب دعم). المسؤول يضيف تعديل المستأجرين والخطط والإصدارات والمشغّلين والإعدادات. وصول الطوارئ صلاحية مسؤول تنتهي خلال ثماني ساعات ويمنحها شخص آخر.",
  ],
  add: ["Add operator", "إضافة مشغّل"],
  addTitle: ["Add an operator", "إضافة مشغّل"],
  addBody: [
    "The person must already have an account (invited through Supabase Auth). They must enroll an authenticator before they can use any page.",
    "يجب أن يكون للشخص حساب مسبقًا (بدعوة عبر Supabase Auth). يجب أن يُعدّ تطبيق مصادقة قبل استخدام أي صفحة.",
  ],
  added: ["Operator added.", "تمت إضافة المشغّل."],
  email: ["Email", "البريد الإلكتروني"],
  role: ["Role", "الدور"],
  expiresAt: ["Access ends (UTC)", "ينتهي الوصول (بالتوقيت العالمي)"],
  expiresHint: [
    "Required for break-glass (at most 8 hours from now); optional otherwise.",
    "مطلوب لوصول الطوارئ (٨ ساعات كحد أقصى)؛ اختياري لغيره.",
  ],
  mfa: ["Authenticator", "تطبيق المصادقة"],
  verified: ["Verified", "موثّق"],
  missing: ["Not enrolled", "غير مُعدّ"],
  status: ["Status", "الحالة"],
  lastSignIn: ["Last sign-in", "آخر تسجيل دخول"],
  usable: ["Counts as a usable administrator", "يُحتسب مسؤولًا فعّالًا"],
  changeRole: ["Change role", "تغيير الدور"],
  changeRoleTitle: ["Change this operator's role", "تغيير دور هذا المشغّل"],
  roleChanged: ["Role changed.", "تم تغيير الدور."],
  disable: ["Revoke access", "إلغاء الوصول"],
  disableTitle: ["Revoke this operator's access?", "إلغاء وصول هذا المشغّل؟"],
  disableBody: [
    "Access ends on their next action and their support access is ended. The last usable administrator cannot be revoked.",
    "ينتهي الوصول مع إجرائه التالي ويُنهى وصول الدعم الخاص به. لا يمكن إلغاء وصول آخر مسؤول فعّال.",
  ],
  disabled: ["Access revoked.", "تم إلغاء الوصول."],
  enable: ["Restore access", "استعادة الوصول"],
  enableTitle: ["Restore this operator's access?", "استعادة وصول هذا المشغّل؟"],
  enabled: ["Access restored.", "تمت استعادة الوصول."],
  actions: ["Actions", "الإجراءات"],
  you: ["(you)", "(أنت)"],
  expires: ["Ends", "ينتهي"],
} as const;

export const accountCopy = {
  title: ["Your account", "حسابك"],
  description: [
    "Your operator standing and second factor.",
    "صلاحيتك كمشغّل وعاملك الثاني.",
  ],
  email: ["Email", "البريد الإلكتروني"],
  role: ["Role", "الدور"],
  expires: ["Access ends", "ينتهي الوصول"],
  lastVerified: ["Last authenticator verification", "آخر تحقق بتطبيق المصادقة"],
  minutesAgo: ["{n} minutes ago", "قبل {n} دقيقة"],
  stepUp: [
    "High-impact actions need a verification within the last {n} minutes; you are asked for a code when needed.",
    "تتطلب الإجراءات عالية الأثر تحققًا خلال آخر {n} دقيقة؛ يُطلب منك رمز عند الحاجة.",
  ],
  verifyNow: ["Verify now", "تحقق الآن"],
  verifiedNow: [
    "Verified. High-impact actions are available for the next few minutes.",
    "تم التحقق. الإجراءات عالية الأثر متاحة للدقائق القادمة.",
  ],
  factors: ["Authenticators", "تطبيقات المصادقة"],
  factorName: ["Name", "الاسم"],
  factorStatus: ["Status", "الحالة"],
  factorCreated: ["Added", "أُضيف"],
  loading: ["Loading authenticators…", "جارٍ تحميل تطبيقات المصادقة…"],
  loadFailed: ["Authenticators could not be loaded.", "تعذّر تحميل تطبيقات المصادقة."],
  recoveryTitle: ["If you lose your authenticator", "إذا فقدت تطبيق المصادقة"],
  recovery: [
    "Platform Admin has no self-service recovery, on purpose. Ask another administrator to revoke your operator access, then ask the platform owner to remove your authenticator factor from the Supabase project (Authentication → Users). Sign in again, enroll a new authenticator, and ask an administrator to restore your access. Every step is recorded.",
    "لا تتيح إدارة المنصة استعادة ذاتية، عن قصد. اطلب من مسؤول آخر إلغاء وصولك، ثم اطلب من مالك المنصة إزالة عامل المصادقة من مشروع Supabase (Authentication ← Users). سجّل الدخول مجددًا، وأعدّ تطبيق مصادقة جديدًا، واطلب من مسؤول استعادة وصولك. تُسجَّل كل خطوة.",
  ],
} as const;

export const auditCopy = {
  title: ["Audit log", "سجل التدقيق"],
  description: [
    "Every operator action, including refused and failed attempts. Entries cannot be edited or deleted.",
    "كل إجراء للمشغّلين، بما فيه المحاولات المرفوضة والفاشلة. لا يمكن تعديل السجلات أو حذفها.",
  ],
  search: [
    "Search actor, action, tenant, target or reason",
    "ابحث بالمنفّذ أو الإجراء أو المستأجر أو الهدف أو السبب",
  ],
  family: ["Area", "المجال"],
  outcome: ["Outcome", "النتيجة"],
  from: ["From (UTC date)", "من (تاريخ)"],
  to: ["To (UTC date)", "إلى (تاريخ)"],
  time: ["Time", "الوقت"],
  actor: ["Operator", "المشغّل"],
  action: ["Action", "الإجراء"],
  target: ["Target", "الهدف"],
  tenant: ["Tenant", "المستأجر"],
  reason: ["Reason", "السبب"],
  detail: ["Detail", "التفاصيل"],
  export: ["Export CSV", "تصدير CSV"],
  exportTitle: ["Export the filtered audit log?", "تصدير سجل التدقيق المصفّى؟"],
  exportBody: [
    "Exports up to 5,000 rows matching the current filters, with redacted detail. The export itself is recorded.",
    "يصدّر حتى ٥٬٠٠٠ صف مطابق لعوامل التصفية الحالية، بتفاصيل منقّحة. يُسجَّل التصدير نفسه.",
  ],
  exported: ["Export downloaded.", "تم تنزيل التصدير."],
  filteredTenant: ["Showing one tenant only.", "عرض مستأجر واحد فقط."],
} as const;

export const settingsCopy = {
  title: ["Settings", "الإعدادات"],
  description: [
    "Fleet-wide flags and banners, and the status of each provider integration.",
    "الإعدادات والتنبيهات على مستوى الأسطول، وحالة كل تكامل مع المزوّدين.",
  ],
  flags: ["Platform flags", "إعدادات المنصة"],
  key: ["Key", "المفتاح"],
  kind: ["Kind", "النوع"],
  enabled: ["On", "مفعّل"],
  messageEn: ["Message (English)", "الرسالة (بالإنجليزية)"],
  messageAr: ["Message (Arabic)", "الرسالة (بالعربية)"],
  startsAt: ["Starts (UTC)", "يبدأ (بالتوقيت العالمي)"],
  endsAt: ["Ends (UTC)", "ينتهي (بالتوقيت العالمي)"],
  updated: ["Last changed", "آخر تعديل"],
  updatedBy: ["Changed by", "عدّله"],
  kinds: {
    feature: ["Feature flag", "مفتاح ميزة"],
    incident_banner: ["Incident banner shown to tenants", "تنبيه حادث يظهر للمستأجرين"],
    maintenance_window: ["Maintenance window", "نافذة صيانة"],
    kill_switch: ["Emergency kill switch", "مفتاح إيقاف طارئ"],
  },
  newFlag: ["New flag", "إعداد جديد"],
  editFlag: ["Edit", "تعديل"],
  flagTitle: ["Platform flag", "إعداد المنصة"],
  flagBody: [
    "Incident banners are shown to every tenant's customers in both languages. Messages are required in both languages or neither.",
    "تظهر تنبيهات الحوادث لعملاء كل مستأجر باللغتين. الرسالة مطلوبة باللغتين أو لا شيء.",
  ],
  flagSaved: ["Flag saved.", "تم حفظ الإعداد."],
  noFlags: ["No platform flags are set.", "لا توجد إعدادات منصة."],
  integrations: ["Integrations", "التكاملات"],
  integrationsNote: [
    'Status comes only from what a worker reported. "Configured" means a worker reported its credentials are present; "reachable" means a connection check succeeded; "verified" means a real operation succeeded. Secrets are never shown or stored here — only the names of the environment variables that hold them.',
    "تأتي الحالة مما أبلغ به العامل فقط. «مهيأ» تعني أن العامل أبلغ بوجود بيانات الاعتماد؛ «يمكن الوصول إليه» تعني نجاح فحص الاتصال؛ «موثّق» تعني نجاح عملية فعلية. لا تُعرض الأسرار ولا تُخزّن هنا — فقط أسماء متغيرات البيئة التي تحملها.",
  ],
  provider: ["Provider", "المزوّد"],
  status: ["Status", "الحالة"],
  references: ["Secret references", "مراجع الأسرار"],
  lastCheck: ["Last connection check", "آخر فحص اتصال"],
  verifiedAt: ["Last verified operation", "آخر عملية موثّقة"],
  check: ["Queue connection check", "جدولة فحص الاتصال"],
  checkQueued: [
    "Check queued. It runs when the integration worker claims it.",
    "تمت جدولة الفحص. يُنفّذ عندما يستلمه عامل التكاملات.",
  ],
  checkPending: [
    "Check queued — waiting for the integration worker",
    "الفحص في الانتظار — بانتظار عامل التكاملات",
  ],
  editReferences: ["Edit references", "تعديل المراجع"],
  referencesTitle: ["Secret references", "مراجع الأسرار"],
  referencesHint: [
    "Environment variable names, one per line, e.g. VERCEL_API_TOKEN. Never paste a secret value.",
    "أسماء متغيرات البيئة، اسم في كل سطر، مثل VERCEL_API_TOKEN. لا تلصق قيمة سرية أبدًا.",
  ],
  referencesSaved: ["References saved.", "تم حفظ المراجع."],
  remaining: [
    "To verify live: deploy the worker with these variables set, then queue a connection check.",
    "للتحقق الفعلي: انشر العامل مع ضبط هذه المتغيرات، ثم جدول فحص الاتصال.",
  ],
} as const;
