export const healthCopy = {
  title: ["Health", "الحالة التشغيلية"],
  description: [
    "Observed instance and integration health, and alerts derived from stored evidence.",
    "حالة النسخ والتكاملات كما رُصدت، والتنبيهات المستخلصة من البيانات المخزنة.",
  ],
  scope: [
    "Only stored observations are shown. Uptime, latency and delivery rates are not collected, so none are displayed. An observation older than 30 minutes is marked stale.",
    "تُعرض الملاحظات المخزنة فقط. لا تُجمع نسب التشغيل أو زمن الاستجابة أو التسليم، لذا لا تُعرض. الملاحظة الأقدم من ٣٠ دقيقة تُعلَّم بأنها قديمة.",
  ],
  alerts: ["Alerts", "التنبيهات"],
  noAlerts: ["No alerts from stored evidence.", "لا توجد تنبيهات من البيانات المخزنة."],
  observations: ["Observations", "الملاحظات"],
  status: ["Status", "الحالة"],
  subject: ["Subject", "الموضوع"],
  kind: ["Kind", "النوع"],
  tenant: ["Tenant", "المستأجر"],
  signal: ["Signal", "المؤشر"],
  observed: ["Observed", "وقت الرصد"],
  freshness: ["Freshness", "الحداثة"],
  kinds: { instance: ["Instance", "نسخة"], integration: ["Integration", "تكامل"] },
  queues: ["Queues", "قوائم الانتظار"],
  queuedJobs: ["Queued jobs", "مهام في الانتظار"],
  failedJobs: ["Failed jobs", "مهام فاشلة"],
  waitingRuns: ["Provisioning waiting", "تهيئة بانتظار"],
} as const;

export const supportCopy = {
  title: ["Support access", "وصول الدعم"],
  description: [
    "Read-only, time-limited access to one tenant, approved by a second administrator and visible to the tenant.",
    "وصول للقراءة فقط ومحدود المدة إلى مستأجر واحد، بموافقة مسؤول ثانٍ ومرئي للمستأجر.",
  ],
  rules: [
    "There is no impersonation: the operator stays themselves, cannot change anything, and access ends at expiry, on revocation, or when their operator access is removed.",
    "لا يوجد انتحال للهوية: يبقى المشغّل بهويته، ولا يمكنه تعديل أي شيء، وينتهي الوصول عند انقضاء المدة أو الإلغاء أو إزالة صلاحيته.",
  ],
  status: ["Status", "الحالة"],
  tenant: ["Tenant", "المستأجر"],
  requestedBy: ["Requested by", "طلبه"],
  approvedBy: ["Approved by", "وافق عليه"],
  ticket: ["Ticket", "التذكرة"],
  reason: ["Reason", "السبب"],
  scope: ["Scope", "النطاق"],
  readOnly: ["Read only", "قراءة فقط"],
  expires: ["Ends", "ينتهي"],
  requested: ["Requested", "وقت الطلب"],
  actions: ["Actions", "الإجراءات"],
  approve: ["Approve", "موافقة"],
  approveTitle: ["Approve this support access?", "الموافقة على وصول الدعم هذا؟"],
  approveBody: [
    "Access starts now and ends after the duration you set. You cannot approve your own request.",
    "يبدأ الوصول الآن وينتهي بعد المدة التي تحددها. لا يمكنك الموافقة على طلبك.",
  ],
  duration: ["Duration (minutes, 5–480)", "المدة (بالدقائق، ٥–٤٨٠)"],
  approved: ["Support access approved.", "تمت الموافقة على وصول الدعم."],
  revoke: ["End access", "إنهاء الوصول"],
  revokeTitle: ["End this support access now?", "إنهاء وصول الدعم الآن؟"],
  revoked: ["Support access ended.", "انتهى وصول الدعم."],
  tenantField: ["Tenant", "المستأجر"],
} as const;
