export const operationsCopy = {
  instances: {
    title: ["Instances", "النسخ"],
    description: [
      "What each instance should run, what it last reported, and whether its infrastructure has drifted.",
      "ما يجب أن تشغّله كل نسخة، وما أبلغت عنه آخر مرة، وما إذا انحرفت بنيتها.",
    ],
    search: ["Search by tenant or instance ID", "ابحث بالمستأجر أو معرّف النسخة"],
    state: ["State", "الحالة"],
    ring: ["Ring", "الحلقة"],
    drift: ["Drift", "الانحراف"],
    driftOnly: ["Drifted only", "المنحرفة فقط"],
    noDrift: ["No drift", "بلا انحراف"],
    tenant: ["Tenant", "المستأجر"],
    instance: ["Instance", "النسخة"],
    release: ["Desired → reported release", "الإصدار المطلوب ← المُبلّغ"],
    infrastructure: [
      "Infrastructure (failing / drifted / total)",
      "البنية (متعطلة / منحرفة / الكل)",
    ],
    health: ["Health", "الحالة التشغيلية"],
    releaseState: ["Release", "الإصدار"],
    configSchema: ["Configuration schema", "مخطط الإعدادات"],
    tier: ["Customization tier", "مستوى التخصيص"],
    contract: ["Supported backend contract", "عقد الخادم المدعوم"],
    environment: ["Environment verified", "تم التحقق من البيئة"],
    reportedAt: ["Last reported", "آخر إبلاغ"],
    resources: ["Infrastructure resources", "موارد البنية"],
    provider: ["Provider", "المزوّد"],
    resource: ["Resource", "المورد"],
    externalId: ["External ID", "المعرّف الخارجي"],
    desired: ["Desired", "المطلوب"],
    observed: ["Observed", "المرصود"],
    observedAt: ["Observed at", "وقت الرصد"],
    attempts: ["Attempts", "المحاولات"],
    lastSuccess: ["Last success", "آخر نجاح"],
    lastError: ["Last error", "آخر خطأ"],
    drifted: ["Drifted", "منحرف"],
    inSync: ["Matches", "مطابق"],
    noResources: [
      "No provider has reported a resource for this instance.",
      "لم يُبلّغ أي مزوّد عن مورد لهذه النسخة.",
    ],
    signals: ["Health signals", "مؤشرات الحالة"],
    signal: ["Signal", "المؤشر"],
    domains: ["Domains", "النطاقات"],
    runs: ["Provisioning runs", "عمليات التهيئة"],
  },
  domains: {
    title: ["Domains", "النطاقات"],
    description: [
      "Every hostname, its verification state and what the provider last reported about its certificate.",
      "كل اسم نطاق، وحالة التحقق، وآخر ما أبلغ به المزوّد عن شهادته.",
    ],
    search: ["Search by hostname or tenant", "ابحث باسم النطاق أو المستأجر"],
    hostname: ["Hostname", "اسم النطاق"],
    tenant: ["Tenant", "المستأجر"],
    application: ["Application", "التطبيق"],
    verification: ["Verification", "التحقق"],
    certificate: ["Certificate", "الشهادة"],
    serving: ["Serving", "قيد الخدمة"],
    pendingJob: ["Verification job", "مهمة التحقق"],
    certificateNote: [
      'Certificate status comes only from the domain worker. "Not reported" means no worker has checked it.',
      "تأتي حالة الشهادة من عامل النطاقات فقط. «لم يُبلّغ عنه» تعني أن أي عامل لم يفحصها.",
    ],
  },
  provisioning: {
    title: ["Provisioning", "التهيئة"],
    description: [
      "Each run is a resumable sequence of steps. Waiting is not failing.",
      "كل عملية سلسلة خطوات قابلة للاستئناف. الانتظار ليس فشلًا.",
    ],
    request: ["Request provisioning", "طلب التهيئة"],
    search: ["Search by slug or tenant", "ابحث بالمعرّف أو المستأجر"],
    state: ["State", "الحالة"],
    inProgress: ["In progress", "قيد التنفيذ"],
    waiting: ["Waiting on others", "بانتظار أطراف أخرى"],
    tenant: ["Tenant", "المستأجر"],
    slug: ["Slug", "المعرّف"],
    steps: ["Steps done", "الخطوات المنجزة"],
    release: ["Release", "الإصدار"],
    updated: ["Updated", "آخر تحديث"],
    newTitle: ["Request provisioning", "طلب التهيئة"],
    newDescription: [
      "Validates everything first and returns every problem at once. Steps that call GitHub or Vercel run only when those workers are deployed with credentials.",
      "يتحقق من كل شيء أولًا ويعيد كل المشكلات دفعة واحدة. الخطوات التي تستدعي GitHub أو Vercel لا تعمل إلا عند نشر تلك العمّال مع بيانات اعتمادها.",
    ],
    target: ["Instance to provision", "النسخة المطلوب تهيئتها"],
    noTargets: [
      "No instance is waiting to be provisioned. Register a tenant first.",
      "لا توجد نسخة بانتظار التهيئة. سجّل مستأجرًا أولًا.",
    ],
    noReleases: [
      "No release is registered. Register one under Releases first.",
      "لا يوجد إصدار مسجّل. سجّل إصدارًا من صفحة الإصدارات أولًا.",
    ],
    slugHint: [
      "Names the repository and projects. 3–40 lowercase letters, digits or hyphens.",
      "يُستخدم لتسمية المستودع والمشاريع. ٣–٤٠ حرفًا صغيرًا أو أرقامًا أو شرطات.",
    ],
    plan: ["Plan", "الخطة"],
    releaseField: ["Release", "الإصدار"],
    defaultLocale: ["Default language", "اللغة الافتراضية"],
    timezone: ["Time zone", "المنطقة الزمنية"],
    timezoneHint: ["IANA name, e.g. Asia/Riyadh.", "اسم IANA، مثل Asia/Riyadh."],
    currency: ["Currency", "العملة"],
    clientHostname: ["Public site domain (optional)", "نطاق الموقع العام (اختياري)"],
    dashboardHostname: [
      "Business dashboard domain (optional)",
      "نطاق لوحة المنشأة (اختياري)",
    ],
    submitted: ["Provisioning requested.", "تم طلب التهيئة."],
    run: ["Run", "التشغيل"],
    waitingReason: ["Waiting for", "بانتظار"],
    lastError: ["Last error", "آخر خطأ"],
    requestedBy: ["Requested by", "طلبه"],
    contract: ["Backend contract", "عقد الخادم"],
    activatedAt: ["Activated", "تاريخ التفعيل"],
    deactivatedAt: ["Deactivated", "تاريخ التعطيل"],
    step: ["Step", "الخطوة"],
    provider: ["Provider", "المزوّد"],
    status: ["Status", "الحالة"],
    attempts: ["Attempts", "المحاولات"],
    started: ["Started", "البداية"],
    lastSuccess: ["Succeeded at", "وقت النجاح"],
    retryAfter: ["Next attempt", "المحاولة التالية"],
    timeline: ["Timeline", "الخط الزمني"],
    retry: ["Retry failed steps", "إعادة محاولة الخطوات الفاشلة"],
    retryTitle: ["Retry this run?", "إعادة محاولة هذه العملية؟"],
    retryBody: [
      "Only failed or abandoned steps restart. Steps that succeeded keep their results.",
      "تُعاد الخطوات الفاشلة أو المتروكة فقط. تحتفظ الخطوات الناجحة بنتائجها.",
    ],
    retried: [
      "Failed steps were reset and will be picked up by their workers.",
      "أُعيد ضبط الخطوات الفاشلة وسيستلمها العمّال.",
    ],
    activate: ["Activate instance", "تفعيل النسخة"],
    activateTitle: ["Activate this instance?", "تفعيل هذه النسخة؟"],
    activateBody: [
      "Activation checks every requirement now and lists anything that blocks it.",
      "يتحقق التفعيل من كل المتطلبات الآن ويعرض ما يمنعه.",
    ],
    activated: ["Instance activated.", "تم تفعيل النسخة."],
    deactivate: ["Deactivate", "تعطيل"],
    deactivateTitle: ["Deactivate this instance?", "تعطيل هذه النسخة؟"],
    deactivateBody: [
      "Marks its resources as no longer wanted and suspends the instance. Nothing is deleted.",
      "يعلّم مواردها كغير مطلوبة ويعلّق النسخة. لا يُحذف شيء.",
    ],
    deactivated: ["Instance deactivated.", "تم تعطيل النسخة."],
    externalWorker: [
      "Runs when the {worker} worker is deployed with its credentials. Until then this step stays pending.",
      "تعمل عند نشر عامل {worker} مع بيانات اعتماده. حتى ذلك الحين تبقى الخطوة معلّقة.",
    ],
  },
  jobs: {
    title: ["Jobs", "المهام"],
    description: [
      "Privileged work is queued here first. A queued job has not run.",
      "يُضاف كل عمل حساس هنا أولًا. المهمة في قائمة الانتظار لم تُنفّذ بعد.",
    ],
    status: ["Status", "الحالة"],
    kind: ["Kind", "النوع"],
    tenant: ["Tenant", "المستأجر"],
    attempts: ["Attempts", "المحاولات"],
    error: ["Last error", "آخر خطأ"],
    requestedBy: ["Requested by", "طلبها"],
    approvedBy: ["Approved by", "وافق عليها"],
    created: ["Created", "تاريخ الإنشاء"],
    completed: ["Completed", "اكتملت"],
    started: ["Started", "بدأت"],
    reason: ["Reason", "السبب"],
    parameters: ["Parameters", "المعاملات"],
    events: ["Events", "الأحداث"],
    lockedUntil: ["Claimed until", "مستلمة حتى"],
    cancel: ["Cancel job", "إلغاء المهمة"],
    cancelTitle: ["Cancel this job?", "إلغاء هذه المهمة؟"],
    cancelBody: [
      "A cancelled job will not run. A running job cannot be cancelled.",
      "لن تُنفّذ المهمة الملغاة. لا يمكن إلغاء مهمة قيد التنفيذ.",
    ],
    cancelled: ["Job cancelled.", "تم إلغاء المهمة."],
    retry: ["Retry job", "إعادة محاولة المهمة"],
    retryTitle: ["Queue this job again?", "إعادة جدولة هذه المهمة؟"],
    retried: ["Job queued again.", "أُعيدت جدولة المهمة."],
    approve: ["Approve", "موافقة"],
    approveTitle: ["Approve this destructive job?", "الموافقة على هذه المهمة الحساسة؟"],
    approveBody: [
      "You are the second administrator. Once approved, a worker may carry it out.",
      "أنت المسؤول الثاني. بعد الموافقة يمكن لعامل تنفيذها.",
    ],
    approved: ["Job approved.", "تمت الموافقة على المهمة."],
    workerNote: [
      "Runs when the {worker} worker claims it. This page shows only what has actually happened.",
      "تُنفّذ عندما يستلمها عامل {worker}. تعرض هذه الصفحة ما حدث فعلًا فقط.",
    ],
  },
  kinds: {
    provision_instance: ["Provision instance", "تهيئة نسخة"],
    seed_repository: ["Seed repository", "تهيئة المستودع"],
    provision_domains: ["Provision domains", "تهيئة النطاقات"],
    publish_release: ["Publish release", "نشر إصدار"],
    rotate_secret: ["Rotate secret", "تدوير سر"],
    suspend_instance: ["Suspend instance", "تعليق نسخة"],
    close_instance: ["Close instance", "إغلاق نسخة"],
    reconcile_drift: ["Reconcile drift", "معالجة الانحراف"],
    verify_domain: ["Verify domain", "التحقق من نطاق"],
    check_integration: ["Check integration", "فحص تكامل"],
  },
  workers: {
    provisioning: ["provisioning", "التهيئة"],
    github: ["GitHub", "غيت هب"],
    vercel: ["Vercel", "فيرسل"],
    resend: ["Resend", "ريسند"],
    domain: ["domain", "النطاقات"],
    release: ["release", "الإصدارات"],
    integration: ["integration check", "فحص التكاملات"],
    infrastructure: ["infrastructure", "البنية"],
    reconciliation: ["reconciliation", "المعالجة"],
  },
  stepNames: {
    validate_request: ["Validate request", "التحقق من الطلب"],
    create_tenant_records: ["Create records", "إنشاء السجلات"],
    seed_repository: ["Create repository", "إنشاء المستودع"],
    commit_configuration: ["Commit configuration", "حفظ الإعدادات"],
    protect_repository: ["Protect repository", "حماية المستودع"],
    create_projects: ["Create projects", "إنشاء المشاريع"],
    configure_mail: ["Configure email", "تهيئة البريد"],
    configure_environment: ["Configure environment", "تهيئة البيئة"],
    deploy_applications: ["Deploy applications", "نشر التطبيقات"],
    verify_domains: ["Verify domains", "التحقق من النطاقات"],
    health_check: ["Health check", "فحص الحالة"],
    generate_agent_pack: ["Generate agent pack", "إنشاء حزمة الوكيل"],
  },
} as const;

/** Which worker a job kind or step provider waits for. */
export const workerForKind: Record<string, keyof typeof operationsCopy.workers> = {
  provision_instance: "provisioning",
  seed_repository: "github",
  provision_domains: "domain",
  verify_domain: "domain",
  publish_release: "release",
  check_integration: "integration",
  reconcile_drift: "reconciliation",
  suspend_instance: "infrastructure",
  close_instance: "infrastructure",
  rotate_secret: "infrastructure",
};
