export const releaseCopy = {
  releases: {
    title: ["Releases", "الإصدارات"],
    description: [
      "Registered versions, what each requires, and which instances want or run it.",
      "الإصدارات المسجّلة، وما يتطلبه كل منها، والنسخ التي تطلبه أو تشغّله.",
    ],
    register: ["Register release", "تسجيل إصدار"],
    registerTitle: ["Register a release", "تسجيل إصدار"],
    registerBody: [
      "Use the values from the generated release manifest (scripts/generate-release-manifest.mjs).",
      "استخدم القيم من ملف الإصدار المُولّد (scripts/generate-release-manifest.mjs).",
    ],
    registered: ["Release registered.", "تم تسجيل الإصدار."],
    version: ["Version", "رقم الإصدار"],
    channel: ["Channel", "القناة"],
    commit: ["Git commit", "التزام Git"],
    configSchema: ["Configuration schema", "مخطط الإعدادات"],
    backendMin: ["Backend contract (min)", "عقد الخادم (أدنى)"],
    backendMax: ["Backend contract (max)", "عقد الخادم (أعلى)"],
    migrations: ["Required migrations", "الترحيلات المطلوبة"],
    migrationsHint: [
      "One migration ID per line, e.g. 20261006120000_platform_admin_foundation.",
      "معرّف ترحيل في كل سطر.",
    ],
    featureNotes: ["Feature notes", "ملاحظات الميزات"],
    upgradeNotes: ["Upgrade notes", "ملاحظات الترقية"],
    notesHint: ["One note per line.", "ملاحظة في كل سطر."],
    reversible: [
      "Can be rolled back safely (no destructive migration)",
      "يمكن التراجع عنه بأمان (لا ترحيل مدمّر)",
    ],
    status: ["Availability", "الإتاحة"],
    contract: ["Backend contract", "عقد الخادم"],
    prerequisites: ["Prerequisites", "المتطلبات المسبقة"],
    ready: ["No blockers right now", "لا توجد عوائق حاليًا"],
    desired: ["Instances wanting it", "نسخ تطلبه"],
    running: ["Instances reporting it", "نسخ تُبلّغ عنه"],
    rollouts: ["Rollouts", "عمليات النشر"],
    registeredBy: ["Registered by", "سجّله"],
    created: ["Registered", "تاريخ التسجيل"],
    notReversible: ["Irreversible", "غير قابل للتراجع"],
    withdraw: ["Withdraw", "سحب"],
    withdrawTitle: ["Withdraw this release?", "سحب هذا الإصدار؟"],
    withdrawBody: [
      "A withdrawn release cannot start new rollouts. Running instances are not changed.",
      "لا يمكن بدء عمليات نشر جديدة لإصدار مسحوب. لا تتغير النسخ العاملة.",
    ],
    makeAvailable: ["Make available", "إتاحة"],
    makeAvailableTitle: [
      "Make this release available again?",
      "إتاحة هذا الإصدار مجددًا؟",
    ],
    statusChanged: ["Availability changed.", "تم تغيير الإتاحة."],
    versions: ["Instance versions", "إصدارات النسخ"],
    tenant: ["Tenant", "المستأجر"],
    desiredRelease: ["Desired", "المطلوب"],
    reportedRelease: ["Reported", "المُبلّغ"],
    reportedAt: ["Reported at", "وقت الإبلاغ"],
    createRollout: ["Create rollout", "إنشاء عملية نشر"],
    createRolloutTitle: ["Create a rollout", "إنشاء عملية نشر"],
    createRolloutBody: [
      "Targets active instances in the chosen rings plus any selected instances. Choose at least one target. Nothing is queued until you start it.",
      "يستهدف النسخ النشطة في الحلقات المختارة بالإضافة إلى النسخ المحددة. اختر هدفًا واحدًا على الأقل. لا تُجدول مهام حتى تبدأه.",
    ],
    instances: ["Specific instances", "نسخ محددة"],
    rings: ["Rings", "الحلقات"],
    rolloutCreated: ["Rollout created as a draft.", "أُنشئت عملية النشر كمسودة."],
    notes: ["Notes", "الملاحظات"],
    empty: ["No releases are registered.", "لا توجد إصدارات مسجّلة."],
  },
  rollouts: {
    title: ["Rollouts", "عمليات النشر"],
    description: [
      "Moving instances to a release. Progress counts only what the release worker reported.",
      "نقل النسخ إلى إصدار. يُحتسب التقدم مما أبلغ به عامل الإصدارات فقط.",
    ],
    status: ["Status", "الحالة"],
    version: ["Release", "الإصدار"],
    rings: ["Rings", "الحلقات"],
    progress: ["Done / failed / queued / total", "منجز / فاشل / بالانتظار / الكل"],
    createdBy: ["Created by", "أنشأها"],
    started: ["Started", "البداية"],
    finished: ["Finished", "النهاية"],
    reason: ["Reason", "السبب"],
    blocked: ["Blocking now", "يمنع حاليًا"],
    targets: ["Targets", "الأهداف"],
    tenant: ["Tenant", "المستأجر"],
    ring: ["Ring", "الحلقة"],
    from: ["From", "من"],
    attempts: ["Attempts", "المحاولات"],
    job: ["Job", "المهمة"],
    reported: ["Reported release", "الإصدار المُبلّغ"],
    history: ["History", "السجل"],
    workerNote: [
      "Queued targets wait for the release worker, which deploys and reports back. Nothing is marked done until it reports.",
      "تنتظر الأهداف عامل الإصدارات الذي ينشر ويُبلّغ. لا يُعدّ شيء منجزًا حتى يُبلّغ.",
    ],
    start: ["Start", "بدء"],
    startTitle: ["Start this rollout?", "بدء عملية النشر؟"],
    startBody: [
      "Checks prerequisites now, sets each target's desired release, and queues one deployment job per target.",
      "يتحقق من المتطلبات الآن، ويضبط الإصدار المطلوب لكل هدف، ويضيف مهمة نشر لكل هدف.",
    ],
    started_ok: [
      "Rollout started; deployments are queued.",
      "بدأت عملية النشر؛ مهام النشر في الانتظار.",
    ],
    resume: ["Resume", "استئناف"],
    pause: ["Pause", "إيقاف مؤقت"],
    pauseTitle: ["Pause this rollout?", "إيقاف عملية النشر مؤقتًا؟"],
    pauseBody: [
      "Unclaimed deployments are withdrawn. Deployments a worker already claimed finish.",
      "تُسحب عمليات النشر غير المستلمة. تكتمل التي استلمها عامل.",
    ],
    paused: ["Rollout paused.", "تم الإيقاف المؤقت."],
    retry: ["Retry failed targets", "إعادة محاولة الأهداف الفاشلة"],
    retryTitle: ["Retry failed targets?", "إعادة محاولة الأهداف الفاشلة؟"],
    retried: ["Failed targets queued again.", "أُعيدت جدولة الأهداف الفاشلة."],
    cancel: ["Cancel rollout", "إلغاء عملية النشر"],
    cancelTitle: ["Cancel this rollout?", "إلغاء عملية النشر؟"],
    cancelled: ["Rollout cancelled.", "أُلغيت عملية النشر."],
    rollback: ["Roll back", "تراجع"],
    rollbackTitle: [
      "Roll back to each instance's previous release?",
      "التراجع إلى الإصدار السابق لكل نسخة؟",
    ],
    rollbackBody: [
      "Queues a deployment of the previous release for each target. Code rollback does not undo data migrations.",
      "يضيف نشر الإصدار السابق لكل هدف. التراجع عن الشيفرة لا يلغي ترحيلات البيانات.",
    ],
    rolledBack: ["Rollback queued.", "تمت جدولة التراجع."],
    rollbackUnavailable: [
      "This release was registered as irreversible, so rollback is not offered. Ship a forward fix.",
      "سُجّل هذا الإصدار كغير قابل للتراجع، لذا لا يُعرض التراجع. انشر إصلاحًا لاحقًا.",
    ],
    empty: ["No rollouts yet.", "لا توجد عمليات نشر بعد."],
  },
} as const;
